create database customer_behavior;
/*Q1. What is the total revenue generated by male vs. female customers?
Q2. Which customers used a discount but still spent more than the average purchase amount?
Q3. Which are the top 5 products with the highest average review rating?
Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
Q8. What are the top 3 most purchased products within each category?
Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Q10. What is the revenue contribution of each age group?*/

USE customer_behavior;

-- Q1. Total revenue (Male vs Female)
SELECT gender, SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer_table
GROUP BY gender;


-- Q2. Discount use kiya but avg se zyada spend
SELECT *
FROM customer_table
WHERE `discount_applied` = 'Yes'
AND `purchase_amount_(usd)` > (
    SELECT AVG(`purchase_amount_(usd)`) FROM customer_table
);


-- Q3. Top 5 products (highest avg rating)
SELECT `item_purchased`, AVG(`review_rating`) AS avg_rating
FROM customer_table
GROUP BY `item_purchased`
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Standard vs Express (avg purchase)
SELECT `shipping_type`, AVG(`purchase_amount_(usd)`) AS avg_purchase
FROM customer_table
GROUP BY `shipping_type`;


-- Q5. Subscribers vs Non-subscribers
SELECT subscription_status,
       AVG(`purchase_amount_(usd)`) AS avg_spend,
       SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer_table
GROUP BY `subscription_status`;


-- Q6. Top 5 products (highest discount %)
SELECT `item_purchased`,
       COUNT(CASE WHEN `discount_applied` = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage
FROM customer_table
GROUP BY `item_purchased`
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Customer Segmentation
SELECT 
    CASE 
        WHEN `previous_purchases` = 0 THEN 'New'
        WHEN `previous_purchases` BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS total_customers
FROM customer_table
GROUP BY customer_segment;


-- Q8. Top 3 products in each category
SELECT `Category`, `item_purchased`, total_purchases
FROM (
    SELECT `category`, `item_purchased`, COUNT(*) AS total_purchases,
           RANK() OVER (PARTITION BY `category` ORDER BY COUNT(*) DESC) AS rnk
    FROM customer_table
    GROUP BY `category`, `item_purchased`
) sub
WHERE rnk <= 3;


-- Q9. Repeat buyers vs Subscription
SELECT 
    CASE 
        WHEN `previous_purchases` > 5 THEN 'Repeat Buyer'
        ELSE 'Normal Buyer'
    END AS buyer_type,
    `subscription_status`,
    COUNT(*) AS total_customers
FROM customer_table
GROUP BY buyer_type, `subscription_status`;


-- Q10. Revenue by Age Group
SELECT 
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS age_group,
    SUM(`purchase_amount_(usd)`) AS total_revenue
FROM
    customer_table
GROUP BY CASE
    WHEN Age BETWEEN 18 AND 25 THEN '18-25'
    WHEN Age BETWEEN 26 AND 35 THEN '26-35'
    WHEN Age BETWEEN 36 AND 50 THEN '36-50'
    ELSE '50+'
END;